apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "docker-auth.name" . }}
  labels:
    app: {{ template "docker-auth.fullname" . }}
    chart: {{ template "docker-auth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "docker-auth.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "docker-auth.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: "docker-auth"
          image: {{ .Values.imageRepository }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ['/docker_auth/auth_server', '-v', '{{ .Values.logVerbosity }}', '/config/auth_config.yml']
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config-secret
              mountPath: /config
            - name: utility-storage
              mountPath: /tokens
{{- if .Values.authCertSecret }}
            - name: auth-cert-secret
              mountPath: {{ .Values.authCertMount}}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: utility-storage
          emptyDir: {}
        - name: config-secret
          secret:
            secretName: docker-auth-config
{{- if .Values.authCertSecret }}
        - name: auth-cert-secret
          secret:
            secretName: {{ .Values.authCertSecret}}
{{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
