apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "authenticated-registry.fullname" . }}
  labels:
    app: {{ template "authenticated-registry.name" . }}
    chart: {{ template "authenticated-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "authenticated-registry.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "authenticated-registry.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.images.auth }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          command: ['--v={{ .Values.log.verbocity }}', '/config/auth_config.yml']
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
      volumes:
        - name: config-volume
          secret:
            secretName: docker-auth-config
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
